
@baseUrl = http://localhost:8080

GET {{baseUrl}}/api/biens/tests
###

###
GET {{baseUrl}}/api/auth/
###
GET {{baseUrl}}/api/biens/gestionnaire?page=1&size=2
###

GET {{baseUrl}}/api/biens/gestionnaire?type=APPARTEMENT&page=0&size=2
###

GET {{baseUrl}}/api/biens/gestionnaire?statut=LOUE&page=0&size=2
###
GET {{baseUrl}}/api/biens/gestionnaire?type=APPARTEMENT&statut=ARCHIVE
###
GET {{baseUrl}}/api/visites/gestionnaire/demande?page=0&size=14

###
PATCH {{baseUrl}}/api/visites/1/approuver
###

PATCH {{baseUrl}}/api/visites/2/refuser
###
POST {{baseUrl}}/api/visites/locataire/2/bien/4
###
GET {{baseUrl}}/api/visites/mes_demandes/1
###
GET {{baseUrl}}/api/visites/biens_disponibles?page=0&size=3

###

GET {{baseUrl}}/api/demandes/locataire/3?statut=EN_ATTENTE
###
POST {{baseUrl}}/api/demandes/locataire/3/bien/1

###
POST {{baseUrl}}/api/biens/create
###
